# Generated by Django 5.2.13 on 2026-05-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('estado_name', models.TextField(unique=True)),
                ('abreviatura', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_estado',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('region_name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_region',
            },
        ),
        migrations.CreateModel(
            name='OOAD',
            fields=[
                ('ooad_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('ooad_name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ooads', to='catalogos.estado')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, related_name='ooads', to='catalogos.region')),
            ],
            options={
                'db_table': 'core_ooad',
            },
        ),
        migrations.CreateModel(
            name='UMAE',
            fields=[
                ('umae_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('umae_name', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='umaes', to='catalogos.estado')),
                ('ooad', models.ForeignKey(db_column='ooad_id', on_delete=django.db.models.deletion.RESTRICT, related_name='umaes', to='catalogos.ooad')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, related_name='umaes', to='catalogos.region')),
            ],
            options={
                'db_table': 'core_umae',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedica',
            fields=[
                ('unidad_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('unidad_name', models.TextField()),
                ('nivel_atencion', models.CharField(choices=[('1', 'Primer Nivel'), ('2', 'Segundo Nivel'), ('3', 'Tercer Nivel')], max_length=1)),
                ('tipo_unidad', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('consultorios_mf', models.IntegerField(default=0)),
                ('consultorios_mf_umtc', models.IntegerField(default=0)),
                ('consultorios_esp', models.IntegerField(default=0)),
                ('quirofanos', models.IntegerField(default=0)),
                ('camas_censables', models.IntegerField(default=0)),
                ('camas_no_censables', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='unidades', to='catalogos.estado')),
                ('ooad', models.ForeignKey(db_column='ooad_id', on_delete=django.db.models.deletion.RESTRICT, related_name='unidades', to='catalogos.ooad')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, related_name='unidades', to='catalogos.region')),
                ('umae', models.ForeignKey(blank=True, db_column='umae_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unidades', to='catalogos.umae')),
            ],
            options={
                'db_table': 'core_unidad_medica',
                'indexes': [models.Index(fields=['ooad'], name='core_unidad_ooad_id_cc87db_idx'), models.Index(fields=['estado'], name='core_unidad_estado__9babbc_idx'), models.Index(fields=['region'], name='core_unidad_region__0e7713_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('consultorios_mf__gte', 0)), name='consultorios_mf_non_negative'), models.CheckConstraint(condition=models.Q(('consultorios_mf_umtc__gte', 0)), name='consultorios_mf_umtc_non_negative'), models.CheckConstraint(condition=models.Q(('consultorios_esp__gte', 0)), name='consultorios_esp_non_negative'), models.CheckConstraint(condition=models.Q(('quirofanos__gte', 0)), name='quirofanos_non_negative'), models.CheckConstraint(condition=models.Q(('camas_censables__gte', 0)), name='camas_censables_non_negative'), models.CheckConstraint(condition=models.Q(('camas_no_censables__gte', 0)), name='camas_no_censables_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('latitud__gte', -90), ('latitud__lte', 90)), ('latitud__isnull', True), _connector='OR'), name='latitud_valid_range'), models.CheckConstraint(condition=models.Q(models.Q(('longitud__gte', -180), ('longitud__lte', 180)), ('longitud__isnull', True), _connector='OR'), name='longitud_valid_range')],
            },
        ),
    ]
