# Generated by Django 5.2.13 on 2026-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_estado_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='abreviatura',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
